<#
.SYNOPSIS
    SOC 1 Audit - Windows Update History Report for Critical SQL Servers

.DESCRIPTION
    Generates a comprehensive Windows Update history report for critical SQL servers
    during the SOC 1 audit period (2025-11-10 to 2025-12-15).
    
    This script provides evidence that patches and upgrades to critical systems
    are tracked and documented for compliance purposes.

.PARAMETER StartDate
    Start date for the audit period (default: 2025-11-10)

.PARAMETER EndDate
    End date for the audit period (default: 2025-12-15)

.PARAMETER OutputPath
    Path where the CSV report will be saved (default: current directory)

.EXAMPLE
    .\Get-WindowsUpdateHistory-SOC1-Audit.ps1
    
    Generates report for default audit period (2025-11-10 to 2025-12-15)

.EXAMPLE
    .\Get-WindowsUpdateHistory-SOC1-Audit.ps1 -StartDate "2025-11-01" -EndDate "2025-12-31"
    
    Generates report for custom date range

.NOTES
    Author: Matthew Thomas
    Purpose: SOC 1 Compliance - CO3 Control
    Control: Patches and upgrades to critical systems are tested and approved 
             prior to being introduced to a production server
    Audit Period: 2025-11-10 to 2025-12-15
    Auditor: Clayton Dicks / Malachy
#>

param(
    [Parameter(Mandatory = $false)]
    [datetime]$StartDate = "2025-11-10",
    
    [Parameter(Mandatory = $false)]
    [datetime]$EndDate = "2025-12-15",
    
    [Parameter(Mandatory = $false)]
    [string]$OutputPath = "."
)

# Critical SQL Servers for SOC 1 Audit
$servers = @(
    "DEVSQL01",
    "PRODSQL01"
)

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "SOC 1 AUDIT - WINDOWS UPDATE HISTORY" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Control: CO3 - Patch Management"
Write-Host "Audit Period: $($StartDate.ToString('yyyy-MM-dd')) to $($EndDate.ToString('yyyy-MM-dd'))"
Write-Host "Auditor: Clayton Dicks / Malachy"
Write-Host "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "Generated By: $env:USERNAME"
Write-Host ""

# Initialize results array
$allUpdates = @()
$serverStatus = @()

foreach ($server in $servers) {
    Write-Host "Processing: $server" -ForegroundColor Yellow
    
    try {
        # Test connectivity
        if (-not (Test-Connection -ComputerName $server -Count 1 -Quiet)) {
            Write-Host "  ✗ Server unreachable" -ForegroundColor Red
            $serverStatus += [PSCustomObject]@{
                Server = $server
                Status = "Unreachable"
                UpdatesFound = 0
            }
            continue
        }
        
        Write-Host "  ✓ Server online" -ForegroundColor Green
        
        # Get Windows Update history using WMI
        Write-Host "  Querying Windows Update history..." -ForegroundColor Gray
        
        $session = New-CimSession -ComputerName $server -ErrorAction Stop
        
        # Query Windows Update history from WMI
        $updates = Get-CimInstance -CimSession $session -ClassName Win32_QuickFixEngineering -ErrorAction Stop |
            Where-Object { 
                $_.InstalledOn -ge $StartDate -and 
                $_.InstalledOn -le $EndDate 
            } |
            Select-Object @{N='Server';E={$server}},
                         @{N='HotFixID';E={$_.HotFixID}},
                         @{N='Description';E={$_.Description}},
                         @{N='InstalledBy';E={$_.InstalledBy}},
                         @{N='InstalledOn';E={$_.InstalledOn}},
                         @{N='Caption';E={$_.Caption}},
                         @{N='Environment';E={if($server -like "*prod*"){"Production"}else{"Development"}}}
        
        Remove-CimSession -CimSession $session
        
        if ($updates) {
            $updateCount = ($updates | Measure-Object).Count
            Write-Host "  ✓ Found $updateCount updates in audit period" -ForegroundColor Green
            $allUpdates += $updates
            
            $serverStatus += [PSCustomObject]@{
                Server = $server
                Status = "Success"
                UpdatesFound = $updateCount
            }
        } else {
            Write-Host "  ⚠ No updates found in audit period" -ForegroundColor Yellow
            $serverStatus += [PSCustomObject]@{
                Server = $server
                Status = "Success"
                UpdatesFound = 0
            }
        }
        
    } catch {
        Write-Host "  ✗ Error: $($_.Exception.Message)" -ForegroundColor Red
        $serverStatus += [PSCustomObject]@{
            Server = $server
            Status = "Error: $($_.Exception.Message)"
            UpdatesFound = 0
        }
    }
    
    Write-Host ""
}

# Generate report filename with timestamp
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$reportFile = Join-Path $OutputPath "SOC1-WindowsUpdates-$timestamp.csv"
$summaryFile = Join-Path $OutputPath "SOC1-WindowsUpdates-Summary-$timestamp.txt"

# Export detailed CSV
if ($allUpdates.Count -gt 0) {
    $allUpdates | Sort-Object Server, InstalledOn | Export-Csv -Path $reportFile -NoTypeInformation
    Write-Host "✓ Detailed report exported: $reportFile" -ForegroundColor Green
} else {
    Write-Host "⚠ No updates found in the specified period" -ForegroundColor Yellow
}

# Generate summary report
$summary = @"
========================================
SOC 1 AUDIT - WINDOWS UPDATE SUMMARY
========================================
Control: CO3 - Patch Management
Requirement: Patches and upgrades to critical systems are tested and approved 
             prior to being introduced to a production server

Audit Period: $($StartDate.ToString('yyyy-MM-dd')) to $($EndDate.ToString('yyyy-MM-dd'))
Report Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Generated By: $env:USERNAME
Auditor: Clayton Dicks / Malachy

========================================
SERVER STATUS
========================================
"@

foreach ($status in $serverStatus) {
    $summary += "`n$($status.Server):"
    $summary += "`n  Status: $($status.Status)"
    $summary += "`n  Updates Found: $($status.UpdatesFound)"
    $summary += "`n"
}

$summary += @"

========================================
UPDATES BY SERVER
========================================
"@

foreach ($server in $servers) {
    $serverUpdates = $allUpdates | Where-Object { $_.Server -eq $server }
    $summary += "`n$server ($($serverUpdates.Count) updates):"
    $summary += "`n" + ("-" * 60)
    
    if ($serverUpdates) {
        foreach ($update in ($serverUpdates | Sort-Object InstalledOn)) {
            $summary += "`n  Date: $($update.InstalledOn.ToString('yyyy-MM-dd'))"
            $summary += "`n  KB: $($update.HotFixID)"
            $summary += "`n  Description: $($update.Description)"
            $summary += "`n  Installed By: $($update.InstalledBy)"
            $summary += "`n"
        }
    } else {
        $summary += "`n  No updates installed during audit period"
        $summary += "`n"
    }
}

$summary += @"

========================================
TOTAL SUMMARY
========================================
Total Servers Checked: $($servers.Count)
Total Updates Found: $($allUpdates.Count)
Development Servers: $(($serverStatus | Where-Object {$_.Server -like '*dev*'}).Count)
Production Servers: $(($serverStatus | Where-Object {$_.Server -like '*prod*'}).Count)

========================================
COMPLIANCE NOTES
========================================
This report provides evidence that:
1. Critical SQL servers are being patched regularly
2. Update history is tracked and auditable
3. Both development and production environments are maintained
4. Patch installation dates and details are documented

For SOC 1 CO3 control compliance, this demonstrates that
patches and upgrades to critical systems are documented and
can be verified for testing and approval processes.

========================================
EVIDENCE GENERATION
========================================
This report was generated using PowerShell WMI queries:
- Query: Get-CimInstance Win32_QuickFixEngineering
- Servers: $($servers -join ', ')
- Date Range: $($StartDate.ToString('yyyy-MM-dd')) to $($EndDate.ToString('yyyy-MM-dd'))
- Method: Remote CIM session to each server
- Output: CSV (detailed) + TXT (summary)

========================================
"@

# Save summary
$summary | Out-File -FilePath $summaryFile -Encoding UTF8
Write-Host "✓ Summary report exported: $summaryFile" -ForegroundColor Green

# Display summary to console
Write-Host "`n$summary" -ForegroundColor Cyan

# Final status
Write-Host "`n=========================================" -ForegroundColor Cyan
Write-Host "AUDIT REPORT COMPLETE" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Files Generated:"
Write-Host "  1. $reportFile (CSV - for spreadsheet analysis)"
Write-Host "  2. $summaryFile (TXT - for audit documentation)"
Write-Host ""
Write-Host "Next Steps for SOC 1 Audit:"
Write-Host "  1. Review the CSV file for detailed update information"
Write-Host "  2. Include both files in audit evidence package"
Write-Host "  3. Take screenshots of this output for audit trail"
Write-Host "  4. Verify updates align with change management records"
Write-Host ""
Write-Host "Auditor: Clayton Dicks / Malachy" -ForegroundColor Yellow
Write-Host "Control: CO3 - Patch Management" -ForegroundColor Yellow
Write-Host "=========================================" -ForegroundColor Cyan

