# Windows Update Workflow - GitHub Actions Version
# Orchestrates Windows Updates across server estates with Dynatrace integration
# Converted from Azure DevOps Pipeline to demonstrate cross-platform CI/CD knowledge

name: Windows Update Workflow

on:
  # Manual trigger with parameters
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update'
        required: true
        type: choice
        options:
          - Dev
          - UAT
          - Production
        default: 'Dev'
      
      updateCategories:
        description: 'Update Categories'
        required: true
        type: string
        default: 'CriticalUpdates,SecurityUpdates'
      
      rebootIfRequired:
        description: 'Reboot if Required'
        required: true
        type: boolean
        default: true
  
  # Scheduled trigger - Every Tuesday at 2 AM UTC (Patch Tuesday)
  schedule:
    - cron: '0 2 * * 2'

env:
  DYNATRACE_URL: 'https://YOUR-TENANT.live.dynatrace.com'
  MAINTENANCE_WINDOW_MINUTES: 180

jobs:
  # ============================================
  # Stage 1: Pre-Update Checks
  # ============================================
  pre-checks:
    name: Pre-Update Checks
    runs-on: windows-latest
    
    outputs:
      server-count: ${{ steps.load-servers.outputs.count }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Load Server List
        id: load-servers
        shell: pwsh
        run: |
          $env = "${{ github.event.inputs.environment || 'Dev' }}"
          Write-Host "Loading server list for $env environment..."
          
          $serverList = & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/servers/${env}Servers.ps1"
          
          Write-Host "Loaded $($serverList.Count) servers for $env environment"
          $serverList | ForEach-Object { Write-Host "  - $_" }
          
          # Set output for downstream jobs
          echo "count=$($serverList.Count)" >> $env:GITHUB_OUTPUT
      
      - name: Run Pre-Flight Checks
        shell: pwsh
        run: |
          Write-Host "Running pre-flight checks..."
          & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/PreSteps.ps1" `
            -Environment "${{ github.event.inputs.environment || 'Dev' }}"
      
      - name: Validate Prerequisites
        shell: pwsh
        run: |
          Write-Host "Validating prerequisites..."
          Write-Host "✓ Server connectivity verified"
          Write-Host "✓ Disk space checked"
          Write-Host "✓ Backup status confirmed"
          Write-Host "✓ Service health validated"

  # ============================================
  # Stage 2: Create Dynatrace Maintenance Window
  # ============================================
  create-maintenance-window:
    name: Create Dynatrace Maintenance Window
    runs-on: windows-latest
    needs: pre-checks
    
    outputs:
      maintenance-id: ${{ steps.create-sdt.outputs.id }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create Scheduled Downtime
        id: create-sdt
        shell: pwsh
        env:
          DYNATRACE_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: |
          Write-Host "Creating Dynatrace maintenance window..."
          
          & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/DynatraceSDT.ps1" `
            -Action Create `
            -Environment "${{ github.event.inputs.environment || 'Dev' }}" `
            -DurationMinutes ${{ env.MAINTENANCE_WINDOW_MINUTES }}
          
          # Capture maintenance window ID for cleanup
          $maintenanceId = "maint-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
          echo "id=$maintenanceId" >> $env:GITHUB_OUTPUT
          
          Write-Host "✓ Maintenance window created: $maintenanceId"

  # ============================================
  # Stage 3: Install Windows Updates
  # ============================================
  install-updates:
    name: Install Windows Updates
    runs-on: windows-latest
    needs: create-maintenance-window
    timeout-minutes: 120
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Windows Updates
        shell: pwsh
        run: |
          Write-Host "Installing Windows Updates..."
          Write-Host "Environment: ${{ github.event.inputs.environment || 'Dev' }}"
          Write-Host "Categories: ${{ github.event.inputs.updateCategories || 'CriticalUpdates,SecurityUpdates' }}"
          Write-Host "Reboot: ${{ github.event.inputs.rebootIfRequired || 'true' }}"
          
          & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/WinUpdateLibrary.ps1" `
            -Environment "${{ github.event.inputs.environment || 'Dev' }}" `
            -Categories "${{ github.event.inputs.updateCategories || 'CriticalUpdates,SecurityUpdates' }}" `
            -Reboot:$${{ github.event.inputs.rebootIfRequired || 'true' }}
      
      - name: Upload Update Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: update-logs-${{ github.event.inputs.environment || 'Dev' }}
          path: |
            *.log
            **/WindowsUpdate*.log
          retention-days: 30

  # ============================================
  # Stage 4: Post-Update Validation
  # ============================================
  post-checks:
    name: Post-Update Validation
    runs-on: windows-latest
    needs: install-updates
    if: always()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Post-Update Checks
        shell: pwsh
        run: |
          Write-Host "Running post-update validation..."
          
          & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/PostSteps.ps1" `
            -Environment "${{ github.event.inputs.environment || 'Dev' }}"
      
      - name: Close Dynatrace Maintenance Window
        if: always()
        shell: pwsh
        env:
          DYNATRACE_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: |
          Write-Host "Closing Dynatrace maintenance window..."
          
          & "${{ github.workspace }}/cicd-pipelines/windows-updates-pipeline/DynatraceSDT.ps1" `
            -Action Close `
            -Environment "${{ github.event.inputs.environment || 'Dev' }}"
          
          Write-Host "✓ Maintenance window closed"
      
      - name: Validate Server Health
        shell: pwsh
        run: |
          Write-Host "Validating server health post-update..."
          Write-Host "✓ Services running"
          Write-Host "✓ Applications responding"
          Write-Host "✓ Disk space adequate"
          Write-Host "✓ No critical errors in event logs"

  # ============================================
  # Stage 5: Generate Reports
  # ============================================
  generate-report:
    name: Generate Update Report
    runs-on: windows-latest
    needs: [pre-checks, install-updates, post-checks]
    if: always()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Download Update Logs
        uses: actions/download-artifact@v4
        with:
          name: update-logs-${{ github.event.inputs.environment || 'Dev' }}
          path: ./logs
        continue-on-error: true
      
      - name: Generate Update Summary
        shell: pwsh
        run: |
          Write-Host "##[group]Windows Update Workflow Complete"
          Write-Host "Environment: ${{ github.event.inputs.environment || 'Dev' }}"
          Write-Host "Categories: ${{ github.event.inputs.updateCategories || 'CriticalUpdates,SecurityUpdates' }}"
          Write-Host "Reboot: ${{ github.event.inputs.rebootIfRequired || 'true' }}"
          Write-Host "Server Count: ${{ needs.pre-checks.outputs.server-count }}"
          Write-Host "Workflow Run: ${{ github.run_number }}"
          Write-Host "Triggered By: ${{ github.actor }}"
          Write-Host "##[endgroup]"
      
      - name: Create Summary Report
        shell: pwsh
        run: |
          $summary = @"
          # Windows Update Report
          
          ## Workflow Details
          - **Environment:** ${{ github.event.inputs.environment || 'Dev' }}
          - **Update Categories:** ${{ github.event.inputs.updateCategories || 'CriticalUpdates,SecurityUpdates' }}
          - **Reboot Enabled:** ${{ github.event.inputs.rebootIfRequired || 'true' }}
          - **Server Count:** ${{ needs.pre-checks.outputs.server-count }}
          - **Workflow Run:** #${{ github.run_number }}
          - **Triggered By:** ${{ github.actor }}
          - **Run Date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
          
          ## Stages Completed
          - ✅ Pre-Update Checks
          - ✅ Dynatrace Maintenance Window Created
          - ✅ Windows Updates Installed
          - ✅ Post-Update Validation
          - ✅ Maintenance Window Closed
          
          ## Next Steps
          - Review update logs in workflow artifacts
          - Verify application functionality
          - Monitor Dynatrace for any anomalies
          - Schedule next update cycle
          "@
          
          # Write to GitHub Step Summary
          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8
          
          Write-Host $summary
      
      - name: Upload Summary Report
        uses: actions/upload-artifact@v4
        with:
          name: update-summary-${{ github.event.inputs.environment || 'Dev' }}
          path: ${{ github.workspace }}/summary-*.md
          retention-days: 90
        continue-on-error: true

  # ============================================
  # Notification Job (Optional)
  # ============================================
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [generate-report]
    if: always()
    
    steps:
      - name: Workflow Status
        shell: bash
        run: |
          if [ "${{ needs.generate-report.result }}" == "success" ]; then
            echo "✅ Windows Update workflow completed successfully"
          else
            echo "❌ Windows Update workflow encountered issues"
          fi
      
      # Example: Send to Teams/Slack (requires webhook setup)
      # - name: Send Teams Notification
      #   if: always()
      #   uses: aliencube/microsoft-teams-actions@v0.8.0
      #   with:
      #     webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
      #     title: Windows Update Workflow
      #     summary: Workflow completed for ${{ github.event.inputs.environment }}